---
- name: Register SSH public key on targets
  hosts: controller
  gather_facts: false

  vars:
    ssl_key_name: id_rsa

  tasks:

    - name: Create a directory to store the SSH key
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'ssh_key_dir', default='/devops/ssh') }}"
        state: directory
        mode: '0700'

    - name: Fetch the public SSH key
      shell: cat "{{ lookup('ansible.builtin.env', 'ssh_key_dir', default='/devops/ssh') }}/{{ ssl_key_name }}.pub"
      register: ssh_key

    - name: Install public keys
      ansible.posix.authorized_key:
        user: "{{ lookup('ansible.builtin.env', 'ssh_user') }}"
        state: present
        key: "{{ item[0] }}"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ ssh_key.stdout }}"
        - "{{ groups['nodes'] }}"

    - name: Change sudoers file
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ lookup('ansible.builtin.env', 'ssh_user') }}"
        state: present
        create: true
        regexp: 'ALL=\(ALL\) NOPASSWD: ALL'
        line: "{{ lookup('ansible.builtin.env', 'ssh_user') }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
      become: true