---
- name: Add ssh key
  hosts: all
  gather_facts: false
  become: false

  tasks:

    - name: Create a directory to store the ssh key
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'ssl_key_dir') }}"
        state: directory
        mode: '0755'
      become: false

    

    - name: Install public keys
      ansible.posix.authorized_key:
        user: "{{ lookup('ansible.builtin.env', 'ssl_user') }}"
        state: present
        key: "{{ lookup('ansible.builtin.env', 'ssl_key_path') }}"
      with_fileglob:
        - "{{ lookup('ansible.builtin.env', 'ssl_key_path') }}.pub"
      become: false

    - name: Change sudoers file
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ lookup('ansible.builtin.env', 'ssl_user') }}"
        state: present
        create: true
        regexp: 'ALL=\(ALL\) NOPASSWD: ALL'
        line: "{{ lookup('ansible.builtin.env', 'ssl_user') }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
      become: true