
- name: Install ansible
  gather_facts: false
  hosts: controller
  become: true

  tasks:

    - name: Install Extra Packages for Enterprise Linux (EPEL)
      ansible.builtin.yum:
        name:
          - epel-release
        state: latest
        update_cache: true

    - name: Install ansible
      ansible.builtin.yum:
        name:
          - ansible
        state: latest
        update_cache: true
