---
- name: Install docker community edition
  gather_facts: false
  hosts: vms

  tasks:

    - name: Install YUM utils
      ansible.builtin.yum:
        name:
          - yum-utils
        state: latest
        update_cache: true
      become: true

    - name: Add Docker repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: true

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
      become: true

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add SSH user to docker group
      ansible.builtin.user:
        name: "{{ lookup('ansible.builtin.env', 'ssh_user') }}"
        groups: docker
        append: yes
      become: true