---
- name: Install docker community edition
  gather_facts: false
  hosts: vms
  become: true

  tasks:

    - name: Install YUM utils
      ansible.builtin.yum:
        name:
          - yum-utils
        state: latest
        update_cache: true

    - name: Add Docker repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add SSH user to docker group
      ansible.builtin.user:
        name: "{{ lookup('ansible.builtin.env', 'ssh_user') }}"
        groups: docker
        append: yes

    - name: Restart docker service, if not started
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: yes