---
- name: Deploy Grafana latest
  hosts: controller
  gather_facts: false

  tasks:

    - name: Ensure the volume is created
      community.docker.docker_volume:
        name: grafana_data
        state: present

    - name: Ensure the monitoring network is created
      community.docker.docker_network:
        name: monitoring_network
        state: present

    - name: Deploy Grafana
      community.docker.docker_container:
        name: grafana
        image: "grafana/grafana:latest"
        ports:
          - "3001:3000"
        volumes:
          - grafana_data:/etc/grafana/
        networks:
          - name: monitoring_network
        restart_policy: unless-stopped
        state: started