- name: Install portainer agent
  hosts: nodes
  gather_facts: false

  tasks:
  
    - name: Install portainer agent
      become: true
      community.docker.docker_container:
        name: "portainer_agent"
        state: started
        container_default_behavior: no_defaults
        image: portainer/agent:latest
        restart_policy: always
        ports:
          - "9001:9001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
          - /:/host