---
- name: Deploy portainer-ce latest
  hosts: all
  become: true

  tasks:
    - name: Create new volume
      community.docker.docker_volume:
        name: portainer-data

    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: unless-stopped