---
- name: Deploy Prometheus latest
  hosts: controller
  gather_facts: false

  tasks:
    - name: Ensure the volume is created
      community.docker.docker_volume:
        name: prometheus_data

    - name: Ensure the monitoring network is created
      community.docker.docker_network:
        name: monitoring_network
        state: present

    - name: Deploy Prometheus
      community.docker.docker_container:
        name: prometheus
        image: "prom/prometheus:latest"
        ports:
          - "9090:9090"
        volumes:
          - "{{ lookup('ansible.builtin.env', 'prometheus_config') }}:/etc/prometheus/prometheus.yml"
          - prometheus_data:/etc/prometheus
        networks:
          - name: monitoring_network
        restart_policy: unless-stopped
        state: started