---
- name: Deploy Semaphore UI for Ansible on Docker
  hosts: all
  become: true

  tasks:

    - name: Creates the temp directory to download the compose file
      ansible.builtin.file:
        path: /tmp/devops/ansible-semaphore/
        state: directory

    - name: Retrieve semaphore docker-compose file from GIT
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ivanfabbri/boilerplate/main/docker-compose/ansible-semaphore/compose.yaml
        dest: /tmp/devops/ansible-semaphore/compose.yaml

    - name: Deploy Semaphore with docker-compose file and start services
      community.docker.docker_compose_v2:
        project_src: /tmp/devops/ansible-semaphore/
        files:
        - compose.yaml
      register: output