---
- name: Update and upgrade yum packages
  hosts: vms
  become: true

  tasks:

    - name: Lists the updates available
      ansible.builtin.yum:
        list: updates
      register: update_list

    - name: Print the available updates
      ansible.builtin.debug:
        var: update_list

    - name: Update all packages with yum
      ansible.builtin.yum:
        name: '*'
        state: latest # noqa: package-latest

    - name: Upgrade packages with yum
      ansible.builtin.yum:
        name: '*'
        state: latest # noqa: package-latest
        exclude: kernel*